version: "3.9"
services:
  
  monitor:
    image: ipfs-monitor
    container_name: monitor
    ports:
      - "3000:3000"
      - "3100:3100"
    networks:
      - node1net
      - node2net
      - node3net
      - node4net
      - node5net

  node1:
    image: ipfs-node
    container_name: node1
    ports:
      - "3031:3030"
      - "4001:4001"
      - "4001:4001/udp"
      - "5001:5001"
      - "8080:8080"
    environment:
      HOST_NAME: node1
    networks:
      - node1net
    depends_on:
      - monitor

  node2:
    image: ipfs-node
    container_name: node2
    ports:
      - "3032:3030"
      - "4002:4001"
      - "4002:4001/udp"
      - "5002:5001"
      - "8081:8080"
    environment:
      HOST_NAME: node2
    networks:
      - node2net
    depends_on:
      - monitor 

  node3:
    image: ipfs-node
    container_name: node3
    ports:
      - "3033:3030"
      - "4003:4001"
      - "4003:4001/udp"
      - "5003:5001"
      - "8082:8080"
    environment:
      HOST_NAME: node3
    networks:
      - node3net
    depends_on:
      - monitor 

  node4:
    image: ipfs-node
    container_name: node4
    ports:
      - "3034:3030"
      - "4004:4001"
      - "4004:4001/udp"
      - "5004:5001"
      - "8083:8080"
    environment:
      HOST_NAME: node4
    networks:
      - node4net
    depends_on:
      - monitor 

  node5:
    image: ipfs-node
    container_name: node5
    ports:
      - "3035:3030"
      - "4005:4001"
      - "4005:4001/udp"
      - "5005:5001"
      - "8084:8080"
    environment:
      HOST_NAME: node5
    networks:
      - node5net
    depends_on:
      - monitor 

networks:
  node1net:
    name: node1net
    external: true
  node2net:
    name: node2net
    external: true
  node3net:
    name: node3net
    external: true
  node4net:
    name: node4net
    external: true
  node5net:
    name: node5net
    external: true
