server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://monitor:3100/loki/api/v1/push

scrape_configs:
- job_name: ipfs
  static_configs:
  - targets:
      - localhost
    labels:
      job: ipfslogs
      __path__: /app/all.log
