{
 "title": "IPFS Measurement Logging",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Node 1",
   "type": "logs",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{host=\"node1\"}"
    }
   ]
  },
  {
   "title": "Node 2",
   "type": "logs",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "{host=\"node2\"}"
    }
   ]
  },
  {
   "title": "Node 3",
   "type": "logs",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "expr": "{host=\"node3\"}"
    }
   ]
  },
  {
   "title": "Node 4",
   "type": "logs",
   "gridPos": { "h": 12, "w": 8, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "{host=\"node4\"}"
    }
   ]
  },
  {
   "title": "Node 5",
   "type": "logs",
   "gridPos": { "h": 12, "w": 8, "x": 8, "y": 10 },
   "targets": [
    {
     "expr": "{host=\"node5\"}"
    }
   ]
  },
  {
   "title": "Log rates",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 8, "x": 16, "y": 10 },
   "targets": [
    {
     "expr": "rate({filename=\"/app/all.log\"}[$__interval])"
    }
   ]
  }
 ]
}